const express = require("express");
const asyncHandler = require("../utils/async-handler");
const controller = require("../controllers/contest.controller");
const { requireAuth } = require("../middleware/auth.middleware");
const requireInternal = require("../middleware/internal.middleware");
const router = express.Router();
router.get("/", asyncHandler(controller.list));
router.post("/challenges", requireAuth, asyncHandler(controller.createChallenge));
router.get("/challenges", requireAuth, asyncHandler(controller.listChallenges));
router.get("/challenges/:challengeId", requireAuth, asyncHandler(controller.getChallenge));
router.get("/:id", asyncHandler(controller.get));
router.get("/:id/standings", asyncHandler(controller.standings));
router.get("/:id/activity", requireAuth, asyncHandler(controller.activity));
router.get("/:id/problems/:problemId", requireAuth, asyncHandler(controller.getProblem));
router.post("/:id/join", requireAuth, asyncHandler(controller.join));
router.post("/:id/run-samples", requireAuth, asyncHandler(controller.runSamples));
router.post("/:id/run", requireAuth, asyncHandler(controller.runCode));
router.get("/:id/submissions/:submissionId", requireAuth, asyncHandler(controller.getSubmission));
router.post("/:id/submissions", requireAuth, asyncHandler(controller.submit));
router.post("/:id/finish", requireAuth, asyncHandler(controller.finish));
router.post("/internal", requireInternal, asyncHandler(controller.create));
router.post("/internal/:id/start", requireInternal, asyncHandler(controller.start));
router.post("/internal/:id/end", requireInternal, asyncHandler(controller.end));
router.post("/internal/:id/cancel", requireInternal, asyncHandler(controller.cancel));
router.post("/internal/:id/bot-submissions", requireInternal, asyncHandler(controller.botSubmission));
module.exports = router;
