const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const crypto = require("crypto");
const { corsOrigins } = require("./config/env");
const routes = require("./routes/contest.routes");
const { notFoundHandler, errorHandler } = require("./middleware/error.middleware");
const app = express();
app.disable("x-powered-by");
app.use(helmet());
app.use(cors({ origin(origin, cb) { if (!origin || corsOrigins.includes(origin)) return cb(null, true); cb(new Error("Origin not allowed by CORS")); } }));
app.use(express.json({ limit: "1mb" }));
app.use((req, res, next) => { req.id = req.header("x-request-id") || crypto.randomUUID(); res.setHeader("x-request-id", req.id); next(); });
app.get("/health", (_req, res) => res.json({ success: true, service: "contest-service", status: "ok" }));
app.use("/api/v1/contests", routes);
app.use(notFoundHandler);
app.use(errorHandler);
module.exports = app;
