const express = require("express");
const cors = require("cors");
const helmet = require("helmet");

const { env, corsOrigins } = require("./config/env");
const requestIdMiddleware = require("./middleware/request-id.middleware");
const blockInternalRoutes = require("./middleware/internal-block.middleware");
const gatewayRoutes = require("./routes/gateway.routes");
const {
  notFoundHandler,
  errorHandler
} = require("./middleware/error.middleware");

const app = express();

if (env.TRUST_PROXY === "true") {
  app.set("trust proxy", 1);
}

app.disable("x-powered-by");

app.use(helmet());

// Give every response generated by this Node process a recognizable marker.
// If a browser receives a 429 without X-CPBOT-Gateway, that response was
// generated before the request reached this application (for example, by an
// upstream edge/proxy) rather than by CP Bot code.
app.use(requestIdMiddleware);
app.use((req, res, next) => {
  const startedAt = Date.now();
  const cfRay = req.header("cf-ray");

  res.setHeader("x-cpbot-gateway", "api-gateway");
  res.setHeader("x-cpbot-build", "no-app-rate-limit-v1");
  if (cfRay) res.setHeader("x-cpbot-cf-ray", cfRay);

  res.on("finish", () => {
    if (res.statusCode >= 400) {
      console.warn("[GATEWAY ERROR RESPONSE]", {
        method: req.method,
        path: req.originalUrl,
        status: res.statusCode,
        durationMs: Date.now() - startedAt,
        requestId: req.id,
        cfRay,
        forwardedFor: req.header("x-forwarded-for"),
      });
    }
  });

  next();
});

// The browser talks to Render from a different origin (Vercel -> Render).
// Cache successful preflight decisions so polling does not create an OPTIONS
// request before every authenticated API request. The cors middleware handles
// OPTIONS automatically, so a second app.options() handler is unnecessary.
app.use(
  cors({
    origin(origin, callback) {
      if (!origin || corsOrigins.includes(origin)) {
        return callback(null, true);
      }

      return callback(new Error("Origin not allowed by CORS"));
    },
    credentials: false,
    methods: ["GET", "HEAD", "PUT", "PATCH", "POST", "DELETE", "OPTIONS"],
    allowedHeaders: ["Authorization", "Content-Type", "X-Request-ID"],
    maxAge: 86400,
    optionsSuccessStatus: 204,
  })
);

// Do not install express.json() globally before the proxy.
// The proxy forwards the original request stream/body directly.
app.get("/health", (_req, res) => {
  res.status(200).json({
    success: true,
    service: "api-gateway",
    status: "ok",
    build: "no-app-rate-limit-v1"
  });
});

app.use("/api/v1", blockInternalRoutes, gatewayRoutes);

app.use(notFoundHandler);
app.use(errorHandler);

module.exports = app;
